version: "2.4"

services:
  nodered:
    image: nodered/node-red:1.0.4-12
    restart: unless-stopped
    ports:
      - 1880:1880
    environment:
      - TZ=Europe/Helsinki
      - BASE_URI=http://localhost:1880
    volumes:
      - "./nodered-data:/data"

  ota-update-server:
    image: registry.cxcorp.systems/ota-update-server
    build: ./ota-update-server
    restart: unless-stopped
    init: true
    environment:
      - HOST=0.0.0.0
      - PORT=4000
      - DEVICE_WHITELIST=["foo"]
      - FW_FOLDER_ID=123123123
      - FW_LATEST_SHEET_ID=123123123
      - FW_VERSION_CACHE_TTL=60000
      - FW_METADATA_CACHE_TTL=600000
      - FW_FILE_CACHE_TTL=86400000
    ports:
      - 4000:4000
    volumes:
      - ./ota-update-server-data/config:/app/config:ro
      - ./ota-update-server-data/firmware:/app/firmware:ro

  bot:
    image: registry.cxcorp.systems/coffee-system-bot
    build: ./bot
    restart: unless-stopped
    init: true
    environment:
      - NODE_ENV=production
      - TZ=Europe/Helsinki
      - TG_TOKEN=<bot token here>
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=coffee
      - PG_PASSWORD=1234
      - PG_DATABASE=coffee
      - NTBA_FIX_350=true

  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      - TZ=Europe/Helsinki
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=coffee
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=coffee
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.7-standalone
    ports:
      - 8080:8080

volumes:
  pg-data:
